server:
  port: 8092

spring:
  application:
    name: mz-service-goods
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml


myname: xuqiang
